version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - app-network

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - app-network

  blockchain-service:
    build: ./blockchain-service
    ports:
      - "3002:3002"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "3003:3003"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
